<hr>

## Fostering reproducibility
### Basic skills
* Software download and installation. 
* Applied bioinformatics, version control, markdown, git, GitHub, R, and RStudio
* Best friend: Google:). Just ask the right question.
* Take advantage of online training materials:
  * Bioinformatics: [Biostar handbook](https://read.biostarhandbook.com/), provide beginner's guide to Bioinformatics and software installation.
  * Fork & Pull request: I bookmarked [this site:)](https://gist.github.com/Chaser324/ce0505fbed06b947d962)

### Hardware  
* Computer with multi-core processor: 64-bit
* Remote Accessory Memory (RAM): 8GB+ 
* Disk space: Tens of gigabytes for small dataset otherwise a few terabytes of storage space may be required for larger datasets.

### Software, language & tools
* R [@R-base]
* Rstudio IDE [Link](https://www.rstudio.com)

### Major R packages
* Rmarkdown [@R-rmarkdown]
* bookdoown [@R-bookdown]
* knitr [@R-knitr]
* ggplot2 [@R-ggplot2]
* dplyr [@R-dplyr]
* shiny [@R-shiny]
* vegan [@R-vegan]
* funModeling [@R-funModeling]

