## Proportion of experimental features

```{r}
library(tm)
set.seed(110912)
text <- readLines("../data/metadata/speciescloud.txt")
# text <- readLines("data/metadata/speciescloud.txt")

# Load the data as a corpus
docs <- Corpus(VectorSource(text))
# inspect(docs)

toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))
docs <- tm_map(docs, toSpace, "/")
docs <- tm_map(docs, toSpace, "@")
docs <- tm_map(docs, toSpace, "\\|")

# Convert the text to lower case
docs <- tm_map(docs, content_transformer(tolower))
docs <- tm_map(docs, removeWords, stopwords("english"))
# Remove punctuations
docs <- tm_map(docs, removePunctuation)
# Eliminate extra white spaces
docs <- tm_map(docs, stripWhitespace)
# Text stemming
# docs <- tm_map(docs, stemDocument)
	tdm <- TermDocumentMatrix(docs)
	m <- as.matrix(tdm)
	v <- sort(rowSums(m),decreasing=TRUE)
	d <- data.frame(word = names(v),freq=v)
``` 

**Freaquency of top 10 variable features**
```{r}
head(d, 10)
```

<br>

**Freaquency of bottom 10 variable features**
```{r}
tail(d, 10)
```

<br>

```{r, include=FALSE}
library(wordcloud2)
set.seed(110912)
# wordcloud2(d)

# Global variables can go here
wordcloud2(d, size = .7, minRotation = -pi/6, maxRotation = pi/6,
  rotateRatio = 1, shape = 'rectangle', color = "random-light", backgroundColor = "black")
```

```{r message=FALSE, warning=FALSE, include=FALSE}
#install webshot
library(webshot)
webshot::install_phantomjs()
```

## Variable features cloud
```{r wordcloud_img}
library(wordcloud2)
set.seed(110912)
# Make the graph
wordgraph=wordcloud2(d, size=0.8)

# save it in html
library("htmlwidgets")
saveWidget(wordgraph,"../img/wordcloud.html",selfcontained = F)

# and in pdf
webshot("../img/wordcloud.html","../img/wordcloud.pdf", delay =15, vwidth = 480, vheight=400)

# and in png
webshot("../img/wordcloud.html","../img/wordcloud.png", delay =15, vwidth = 480, vheight=400)
```

